// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqukDTvAylojfyG_a4bK-sHaQtRxaneM',
    appId: '1:941191006628:web:507789dc8df6f3be775931',
    messagingSenderId: '941191006628',
    projectId: 'footware-50e9c',
    authDomain: 'footware-50e9c.firebaseapp.com',
    storageBucket: 'footware-50e9c.appspot.com',
    measurementId: 'G-569HN34TXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTNKf4pNX6_8PuJJwDnMz2IfZGI37AAM8',
    appId: '1:941191006628:android:a8447484bfbaae10775931',
    messagingSenderId: '941191006628',
    projectId: 'footware-50e9c',
    storageBucket: 'footware-50e9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuZgEj4EE5TOktoZ2Xn1D6JicSp99afu8',
    appId: '1:941191006628:ios:4d67a60304a7dcfc775931',
    messagingSenderId: '941191006628',
    projectId: 'footware-50e9c',
    storageBucket: 'footware-50e9c.appspot.com',
    iosBundleId: 'com.example.footwareUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuZgEj4EE5TOktoZ2Xn1D6JicSp99afu8',
    appId: '1:941191006628:ios:4d67a60304a7dcfc775931',
    messagingSenderId: '941191006628',
    projectId: 'footware-50e9c',
    storageBucket: 'footware-50e9c.appspot.com',
    iosBundleId: 'com.example.footwareUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcqukDTvAylojfyG_a4bK-sHaQtRxaneM',
    appId: '1:941191006628:web:b88e2b12b98014bb775931',
    messagingSenderId: '941191006628',
    projectId: 'footware-50e9c',
    authDomain: 'footware-50e9c.firebaseapp.com',
    storageBucket: 'footware-50e9c.appspot.com',
    measurementId: 'G-ZGZL5P4F8C',
  );
}
